
###########mall hystrix 熔断设计
server:
  port: 9010
  servlet:
    #应用访问名称
    context-path: /mall-hystrix


  #eureka相关配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
      server9002: http://127.0.0.1:9002/eureka/
    enabled: true


  #spring应用相关配置
spring:
  application:
    #应用服务名称
    name: mall-hystrix


debug: true
hystrix:
  metrics:
    enabled: true

