
###########mall service 后端服务
server:
  port: 8010
  #servlet:
    #应用访问名称
  #  context-path: /mall-server


  #eureka相关配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
      server9002: http://127.0.0.1:9002/eureka/
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}:@pom.version@


  #spring应用相关配置
spring:
  application:
    #应用服务名称--将会显示在eureka服务界面中
    name: @pom.artifactId@

#debug: true

#开启日志级别
logging:
  level:
    root: debug
