server:
  port: 9002


##eureka相关配置
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #表示是否注册自身到eureka服务器
    register-with-eureka: false
    #是否从eureka上获取注册信息
    fetch-registry: false
    eureka-server-port: 9001
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      server9001: http://${eureka.instance.hostname}:9001/eureka/


spring